name: Run test

on:
  push:
    branches:
      - main
    paths:
      - "services/**"
      - ".github/workflows/test.yaml"
      
  pull_request:
  workflow_dispatch:


jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: filter
        id: filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          filters: .github/utils/file-filter.yaml

  test:
    runs-on: ubuntu-latest
    needs: filter
    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJson(needs.filter.outputs.services) }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node
        if: ${{ startsWith(matrix.service, 'services/node') || startsWith(matrix.service, 'services/react') }}
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ matrix.service }}/package.json
          cache: npm
          cache-dependency-path: ${{ matrix.service }}/package-lock.json

      - name: Setup Go
        if: ${{ startsWith(matrix.service, 'services/go') }}
        uses: actions/setup-go@v4
        with:
          go-version-file: ${{ matrix.service }}/go.mod
          cache-dependency-path: ${{ matrix.service }}/go.sum

      - name: Setup Poetry
        if: ${{ startsWith(matrix.service, 'services/python') }}
        uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a # v1.4.1
      - name: Setup Python
        if: ${{ startsWith(matrix.service, 'services/python') }}
        uses: actions/setup-python@v4
        with:
          python-version-file: ${{ matrix.service }}/pyproject.toml
          cache: pip
          cache-dependency-path: ${{ matrix.service }}/pyproject.toml

      - name: Install Task
        uses: supplypike/setup-bin@v4
        with:
          uri: https://github.com/go-task/task/releases/download/v3.45.5/task_linux_amd64.tar.gz
          name: task
          version: v3.45.5
      - name: Install app dependencies
        working-directory: ${{ matrix.service }}
        run: |
          task install-ci
      - name: Run tests
        working-directory: ${{ matrix.service }}
        run: |
          task test